### ISSUE TITLE
AttributeError: 'SubwordXLMForTokenClassification' object has no attribute 'split'

### ISSUE THREAD

**Issue by benx13** [segment-any-text/wtpsplit#140]
been getting recently:

Traceback (most recent call last):
  File "/home/server/grog/test.py", line 8, in <module>
    r = sat.split("This is a test This is another test.")
  File "/home/server/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'SubwordXLMForTokenClassification' object has no attribute 'split'

code to reproduce:

```
from wtpsplit import SaT

sat = SaT("sat-3l-sm").half().to('cuda')
r = sat.split("This is a test This is another test.")
print(r)
```

wtpsplit     2.1.1
torch          2.5.1

Happened on two machines now:
M1 Pro Mac with python 3.9
ubuntu 22 cuda enabled with python 3.10

**Comment by benx13** [comment]
CPU version seems to be working, cuda and mps same error

**Comment by benx13** [comment]
The issue seems to be due to chaining .to(device) immediately after model instantiation. Apparently, it cause the wrong model class to be used.
```
sat = SaT("sat-3l-sm")
sat.half().to("mps")
```
this fixes it
